### ISSUE TITLE
`make run` is unfriendly to parallel builds

### ISSUE THREAD

**Issue by Hoblovski** [wangrunji0408/RustOS#2]
At [this line of code](https://github.com/wangrunji0408/RustOS/blob/master/kernel/Makefile#L97), if we execute `make run -j4` then it'll incorrectly build iso and run qemu at the same time.

**Comment by wangrunji0408** [comment]
Do you have any solution? 😂

**Comment by wangrunji0408** [comment]
I'm working on using [bootimage](https://github.com/rust-osdev/bootimage) to replace the current ugly build process (maybe for x86_64 only). Wish all these problems will disappear after that.

**Comment by Hoblovski** [comment]
Great

**Comment by Hoblovski** [comment]
@wangrunji0408 I found another problem.

The parallel options passed to `make` does not go into `cargo`, so `make -j8 iso` is of no use, just the same as `make iso`.

Hope this will be fixed in the future.

**Comment by wangrunji0408** [comment]
It seems `cargo` already support parallel build.
So there is no need to parallel `make`.
