### ISSUE TITLE
Is pagefault on RISC-V supported?

### ISSUE THREAD

**Issue by Hoblovski** [wangrunji0408/RustOS#3]
I searched through the source code (crate/riscv and kernel/src/arch),
but could not find any code piece related to pagefault handing on rv.

**Comment by wangrunji0408** [comment]
For now, there is no special page fault handler on RV32. I just treat it as a normal exception.
It should be like [x86_64 version](https://github.com/wangrunji0408/RustOS/blob/30a569d8896de7d4e7f75bf02dc688677ad604b2/kernel/src/arch/x86_64/interrupt/handler.rs#L115): jump to [this function](https://github.com/wangrunji0408/RustOS/blob/30a569d8896de7d4e7f75bf02dc688677ad604b2/kernel/src/memory.rs#L48) and do some swapping or copy-on-write.

**Comment by Hoblovski** [comment]
Great answer ;)
